---
name: "Session Cleaner"
guid: "EC9E2A74-1311-4A14-B302-158E3D95FD1D"
version: 4
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Stops paused sessions."
description: >
  Stops paused sessions after x amount of seconds.

category: "Administration"
artifacts:
  - "Jellyfin.Plugin.StopSessions.dll"
changelog: |-
