---
name: "Stop Sessions"
guid: "28a6125c-cb57-4e8b-b031-421ac55cfa91"
version: 1
targetAbi: "10.10.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Stops paused sessions."
description: >
  Stops paused sessions after a specified amount of time.

category: "Administration"
artifacts:
  - "Jellyfin.Plugin.StopSessions.dll"
changelog: |-
